"""add support for flags

Revision ID: e7b1be22f200
Revises: 85117bbba937
Create Date: 2023-10-08 09:27:59.456659+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e7b1be22f200'
down_revision: Union[str, None] = '85117bbba937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'logflag',
        sa.Column('log_id', sa.Integer(), nullable=False),
        sa.Column('flag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(['log_id'], ['log.id'], ),
        sa.PrimaryKeyConstraint('log_id', 'flag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logflag')
    # ### end Alembic commands ###
